CREATE TABLE facilities (
    FACILITY_ID SERIAL PRIMARY KEY,
    FACILITY_STATE VARCHAR(2) NOT NULL,
    FACILITY_CITY TEXT NOT NULL,
    FACILITY_NAME TEXT NOT NULL,
    FACILITY_TYPE VARCHAR(16) NOT NULL,
    POSTAL_CODE VARCHAR(9) NOT NULL
);

CREATE TABLE transactions (
    TRANSACTION_ID SERIAL PRIMARY KEY,
    FISCAL_YEAR INTEGER NOT NULL,
    SUBMISSION_DATE DATE NOT NULL,
    FACILITY_ID INTEGER NOT NULL,  -- Linking to facilities
    ACCOUNTING_CENTRE VARCHAR(5) NOT NULL,
    FINANCIAL_ACCOUNT VARCHAR(4) NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (FACILITY_ID) REFERENCES facilities(FACILITY_ID) ON DELETE CASCADE
);

